name: aapkavaidya
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  liquid_swipe: ^1.4.3
  flutter_icons: ^1.0.0+1
  provider: 
  flutter_share: ^1.0.2+1
  cached_network_image:
  flutter_launcher_icons: ^0.7.4
  firebase_auth:
  google_sign_in:
  flutter_custom_clippers: ^1.1.0
  cloud_firestore:
  firebase_storage:
  fluttertoast:
  image_picker:
  giffy_dialog:
  firebase_core: ^0.4.3+2
  firebase_database:
  shared_preferences: ^0.5.7
  connectivity: ^0.4.8+2
  flutter_auth_buttons: ^0.3.1
  share: ^0.6.2+3
  url_launcher: ^5.4.1
  link: ^1.0.0
  rflutter_alert: ^1.0.3
  http: ^0.12.0+2
  youtube_player_flutter: ^6.0.3+2
  music_player: ^0.1.4
  path_provider:
  flutter_cache_manager:
  search_page: ^1.2.0
  google_maps_flutter: ^0.5.11
  flutter_facebook_login: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.0"

flutter_icons:
  ios: true
  android: true
  image_path_ios: "img/logo.png"
  image_path_android: "img/logo.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/videos/intro.mp4
  #  - images/a_dot_ham.jpeg
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf
    - family: Baloo
      fonts:
        - asset: assets/fonts/Baloo-Regular.ttf
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
